<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Quiz extends Model
{
    protected $fillable = [
        'title',
        'note_id',
        'user_id',
        'questions',
        'content_analysis',
        'total_questions',
        'estimated_time',
        'difficulty_level',
        'quiz_metadata',
        'is_active',
        'is_random'
    ];

    protected $casts = [
        'questions' => 'array',
        'content_analysis' => 'array',
        'quiz_metadata' => 'array',
        'is_active' => 'boolean',
        'is_random' => 'boolean',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];

    /**
     * Get the note that this quiz belongs to
     */
    public function note(): BelongsTo
    {
        return $this->belongsTo(Note::class);
    }

    /**
     * Get the user who created this quiz
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * Get all questions for this quiz
     */
    public function questions(): HasMany
    {
        return $this->hasMany(Question::class);
    }

    /**
     * Get all attempts for this quiz
     */
    public function attempts(): HasMany
    {
        return $this->hasMany(QuizAttempt::class);
    }

    /**
     * Get the latest attempt for this quiz by a specific user
     */
    public function latestAttemptByUser($userId)
    {
        return $this->attempts()
            ->where('user_id', $userId)
            ->latest()
            ->first();
    }

    /**
     * Get the best attempt for this quiz by a specific user
     */
    public function bestAttemptByUser($userId)
    {
        return $this->attempts()
            ->where('user_id', $userId)
            ->orderBy('percentage', 'desc')
            ->first();
    }

    /**
     * Get average score for this quiz
     */
    public function getAverageScoreAttribute()
    {
        return $this->attempts()
            ->where('completed_at', '!=', null)
            ->avg('percentage') ?: 0;
    }

    /**
     * Get total number of attempts
     */
    public function getTotalAttemptsAttribute()
    {
        return $this->attempts()
            ->where('completed_at', '!=', null)
            ->count();
    }

    /**
     * Check if quiz was generated by ML
     */
    public function getIsMLGeneratedAttribute()
    {
        return isset($this->quiz_metadata['generated_by']) && 
               $this->quiz_metadata['generated_by'] === 'ml_service';
    }

    /**
     * Get formatted estimated time
     */
    public function getFormattedEstimatedTimeAttribute()
    {
        if ($this->estimated_time < 60) {
            return $this->estimated_time . ' min';
        }
        
        $hours = floor($this->estimated_time / 60);
        $minutes = $this->estimated_time % 60;
        
        return $hours . 'h ' . $minutes . 'm';
    }

    /**
     * Get difficulty level badge class
     */
    public function getDifficultyBadgeClassAttribute()
    {
        return match($this->difficulty_level) {
            'easy' => 'bg-success',
            'medium' => 'bg-warning',
            'hard' => 'bg-danger',
            default => 'bg-secondary'
        };
    }

    /**
     * Get questions by type
     */
    public function getQuestionsByType(string $type): array
    {
        return $this->questions[$type] ?? [];
    }

    /**
     * Get all question types available in this quiz
     */
    public function getAvailableQuestionTypes(): array
    {
        if (!is_array($this->questions)) {
            return [];
        }
        
        return array_keys(array_filter($this->questions, function($questions) {
            return !empty($questions);
        }));
    }

    /**
     * Scope to get active quizzes only
     */
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    /**
     * Scope to get quizzes by difficulty
     */
    public function scopeByDifficulty($query, string $difficulty)
    {
        return $query->where('difficulty_level', $difficulty);
    }

    /**
     * Scope to get ML-generated quizzes
     */
    public function scopeMLGenerated($query)
    {
        return $query->whereJsonContains('quiz_metadata->generated_by', 'ml_service');
    }
}
